definitions:
  loginModel.ReqLogin:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  loginModel.ResLogin:
    properties:
      name:
        type: string
      token:
        type: string
      userid:
        type: integer
      username:
        type: string
    type: object
  reportDTO.ResInfoOmzetMerchant:
    properties:
      messages:
        example: Success
        type: string
      result:
        $ref: '#/definitions/reportModel.ResOmzetMerchant'
      status:
        example: 200
        type: integer
    type: object
  reportDTO.ResInfoOmzetOutlet:
    properties:
      messages:
        example: Success
        type: string
      result:
        $ref: '#/definitions/reportModel.ResOmzetOutlet'
      status:
        example: 200
        type: integer
    type: object
  reportModel.DataOmzetMerchants:
    properties:
      merchant_name:
        type: string
      name:
        type: string
      omzet:
        type: number
      tanggal:
        type: string
      userid:
        type: integer
    type: object
  reportModel.DataOmzetOutlets:
    properties:
      merchant_name:
        type: string
      name:
        type: string
      omzet:
        type: number
      outlet_name:
        type: string
      tanggal:
        type: string
      userid:
        type: integer
    type: object
  reportModel.ReqOmzetMerchant:
    properties:
      row_per_page:
        type: integer
      start:
        type: integer
      userid:
        type: integer
    type: object
  reportModel.ResOmzetMerchant:
    properties:
      data:
        items:
          $ref: '#/definitions/reportModel.DataOmzetMerchants'
        type: array
      row_per_page:
        type: integer
      start:
        type: integer
    type: object
  reportModel.ResOmzetOutlet:
    properties:
      data:
        items:
          $ref: '#/definitions/reportModel.DataOmzetOutlets'
        type: array
      row_per_page:
        type: integer
      start:
        type: integer
    type: object
  userDTO.ResLoginResult:
    properties:
      messages:
        example: Login Success
        type: string
      result:
        $ref: '#/definitions/loginModel.ResLogin'
      status:
        example: 200
        type: integer
    type: object
  userDTO.ResNotFound:
    properties:
      messages:
        example: Wrong Username
        type: string
      status:
        example: 404
        type: integer
    type: object
info:
  contact:
    email: m.nurbasari@gmail.com
    name: Muhammadnurbasari
  description: TEST BE MAJOO
  title: TEST BE MAJOO
  version: 0.0.1
paths:
  /report/omzet-merchant:
    post:
      consumes:
      - application/json
      description: get data and pagination omzet merchants
      parameters:
      - description: page info
        in: body
        name: pageInfo
        required: true
        schema:
          $ref: '#/definitions/reportModel.ReqOmzetMerchant'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reportDTO.ResInfoOmzetMerchant'
      summary: get data and pagination omzet merchants
      tags:
      - Reports
  /report/omzet-outlet:
    post:
      consumes:
      - application/json
      description: get data and pagination omzet merchants
      parameters:
      - description: page info
        in: body
        name: pageInfo
        required: true
        schema:
          $ref: '#/definitions/reportModel.ReqOmzetMerchant'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reportDTO.ResInfoOmzetOutlet'
      summary: get data and pagination omzet merchants
      tags:
      - Reports
  /user/login:
    post:
      consumes:
      - application/json
      description: Login endpoint to get Authorization token
      operationId: login-username-password
      parameters:
      - description: Auth info
        in: body
        name: authinfo
        required: true
        schema:
          $ref: '#/definitions/loginModel.ReqLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userDTO.ResLoginResult'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/userDTO.ResNotFound'
      summary: Login by username and password, please try using POSTMAN
      tags:
      - Authentication
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
