info:
  contact:
    email: m.nurbasari@gmail.com
    name: Muhammadnurbasari
  description: Service bdj
  title: SERVICE BDJ
  version: 0.1.5
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
